version: "3.2"
services:
  mysql:
    image: mysql:8
    container_name: 'mysql'
    environment:
      MYSQL_DATABASE: 'task_scheduler'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3320:3306'
    expose:
      - '3320'
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'