// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"github.com/Av1shay/timers-scheduler-demo/ent/predicate"
	"github.com/Av1shay/timers-scheduler-demo/ent/task"
	"github.com/Av1shay/timers-scheduler-demo/ent/taskhistory"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskHistoryQuery is the builder for querying TaskHistory entities.
type TaskHistoryQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TaskHistory
	withTask   *TaskQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TaskHistoryQuery builder.
func (thq *TaskHistoryQuery) Where(ps ...predicate.TaskHistory) *TaskHistoryQuery {
	thq.predicates = append(thq.predicates, ps...)
	return thq
}

// Limit adds a limit step to the query.
func (thq *TaskHistoryQuery) Limit(limit int) *TaskHistoryQuery {
	thq.limit = &limit
	return thq
}

// Offset adds an offset step to the query.
func (thq *TaskHistoryQuery) Offset(offset int) *TaskHistoryQuery {
	thq.offset = &offset
	return thq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (thq *TaskHistoryQuery) Unique(unique bool) *TaskHistoryQuery {
	thq.unique = &unique
	return thq
}

// Order adds an order step to the query.
func (thq *TaskHistoryQuery) Order(o ...OrderFunc) *TaskHistoryQuery {
	thq.order = append(thq.order, o...)
	return thq
}

// QueryTask chains the current query on the "task" edge.
func (thq *TaskHistoryQuery) QueryTask() *TaskQuery {
	query := &TaskQuery{config: thq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := thq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := thq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(taskhistory.Table, taskhistory.FieldID, selector),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, taskhistory.TaskTable, taskhistory.TaskColumn),
		)
		fromU = sqlgraph.SetNeighbors(thq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TaskHistory entity from the query.
// Returns a *NotFoundError when no TaskHistory was found.
func (thq *TaskHistoryQuery) First(ctx context.Context) (*TaskHistory, error) {
	nodes, err := thq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{taskhistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (thq *TaskHistoryQuery) FirstX(ctx context.Context) *TaskHistory {
	node, err := thq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TaskHistory ID from the query.
// Returns a *NotFoundError when no TaskHistory ID was found.
func (thq *TaskHistoryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = thq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{taskhistory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (thq *TaskHistoryQuery) FirstIDX(ctx context.Context) int {
	id, err := thq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TaskHistory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TaskHistory entity is found.
// Returns a *NotFoundError when no TaskHistory entities are found.
func (thq *TaskHistoryQuery) Only(ctx context.Context) (*TaskHistory, error) {
	nodes, err := thq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{taskhistory.Label}
	default:
		return nil, &NotSingularError{taskhistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (thq *TaskHistoryQuery) OnlyX(ctx context.Context) *TaskHistory {
	node, err := thq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TaskHistory ID in the query.
// Returns a *NotSingularError when more than one TaskHistory ID is found.
// Returns a *NotFoundError when no entities are found.
func (thq *TaskHistoryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = thq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{taskhistory.Label}
	default:
		err = &NotSingularError{taskhistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (thq *TaskHistoryQuery) OnlyIDX(ctx context.Context) int {
	id, err := thq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TaskHistories.
func (thq *TaskHistoryQuery) All(ctx context.Context) ([]*TaskHistory, error) {
	if err := thq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return thq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (thq *TaskHistoryQuery) AllX(ctx context.Context) []*TaskHistory {
	nodes, err := thq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TaskHistory IDs.
func (thq *TaskHistoryQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := thq.Select(taskhistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (thq *TaskHistoryQuery) IDsX(ctx context.Context) []int {
	ids, err := thq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (thq *TaskHistoryQuery) Count(ctx context.Context) (int, error) {
	if err := thq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return thq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (thq *TaskHistoryQuery) CountX(ctx context.Context) int {
	count, err := thq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (thq *TaskHistoryQuery) Exist(ctx context.Context) (bool, error) {
	if err := thq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return thq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (thq *TaskHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := thq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TaskHistoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (thq *TaskHistoryQuery) Clone() *TaskHistoryQuery {
	if thq == nil {
		return nil
	}
	return &TaskHistoryQuery{
		config:     thq.config,
		limit:      thq.limit,
		offset:     thq.offset,
		order:      append([]OrderFunc{}, thq.order...),
		predicates: append([]predicate.TaskHistory{}, thq.predicates...),
		withTask:   thq.withTask.Clone(),
		// clone intermediate query.
		sql:    thq.sql.Clone(),
		path:   thq.path,
		unique: thq.unique,
	}
}

// WithTask tells the query-builder to eager-load the nodes that are connected to
// the "task" edge. The optional arguments are used to configure the query builder of the edge.
func (thq *TaskHistoryQuery) WithTask(opts ...func(*TaskQuery)) *TaskHistoryQuery {
	query := &TaskQuery{config: thq.config}
	for _, opt := range opts {
		opt(query)
	}
	thq.withTask = query
	return thq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Error string `json:"error,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TaskHistory.Query().
//		GroupBy(taskhistory.FieldError).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (thq *TaskHistoryQuery) GroupBy(field string, fields ...string) *TaskHistoryGroupBy {
	grbuild := &TaskHistoryGroupBy{config: thq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := thq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return thq.sqlQuery(ctx), nil
	}
	grbuild.label = taskhistory.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Error string `json:"error,omitempty"`
//	}
//
//	client.TaskHistory.Query().
//		Select(taskhistory.FieldError).
//		Scan(ctx, &v)
//
func (thq *TaskHistoryQuery) Select(fields ...string) *TaskHistorySelect {
	thq.fields = append(thq.fields, fields...)
	selbuild := &TaskHistorySelect{TaskHistoryQuery: thq}
	selbuild.label = taskhistory.Label
	selbuild.flds, selbuild.scan = &thq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a TaskHistorySelect configured with the given aggregations.
func (thq *TaskHistoryQuery) Aggregate(fns ...AggregateFunc) *TaskHistorySelect {
	return thq.Select().Aggregate(fns...)
}

func (thq *TaskHistoryQuery) prepareQuery(ctx context.Context) error {
	for _, f := range thq.fields {
		if !taskhistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if thq.path != nil {
		prev, err := thq.path(ctx)
		if err != nil {
			return err
		}
		thq.sql = prev
	}
	return nil
}

func (thq *TaskHistoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TaskHistory, error) {
	var (
		nodes       = []*TaskHistory{}
		withFKs     = thq.withFKs
		_spec       = thq.querySpec()
		loadedTypes = [1]bool{
			thq.withTask != nil,
		}
	)
	if thq.withTask != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, taskhistory.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TaskHistory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TaskHistory{config: thq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, thq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := thq.withTask; query != nil {
		if err := thq.loadTask(ctx, query, nodes, nil,
			func(n *TaskHistory, e *Task) { n.Edges.Task = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (thq *TaskHistoryQuery) loadTask(ctx context.Context, query *TaskQuery, nodes []*TaskHistory, init func(*TaskHistory), assign func(*TaskHistory, *Task)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*TaskHistory)
	for i := range nodes {
		if nodes[i].task_histories == nil {
			continue
		}
		fk := *nodes[i].task_histories
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(task.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "task_histories" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (thq *TaskHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := thq.querySpec()
	_spec.Node.Columns = thq.fields
	if len(thq.fields) > 0 {
		_spec.Unique = thq.unique != nil && *thq.unique
	}
	return sqlgraph.CountNodes(ctx, thq.driver, _spec)
}

func (thq *TaskHistoryQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := thq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (thq *TaskHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   taskhistory.Table,
			Columns: taskhistory.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: taskhistory.FieldID,
			},
		},
		From:   thq.sql,
		Unique: true,
	}
	if unique := thq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := thq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taskhistory.FieldID)
		for i := range fields {
			if fields[i] != taskhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := thq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := thq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := thq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := thq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (thq *TaskHistoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(thq.driver.Dialect())
	t1 := builder.Table(taskhistory.Table)
	columns := thq.fields
	if len(columns) == 0 {
		columns = taskhistory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if thq.sql != nil {
		selector = thq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if thq.unique != nil && *thq.unique {
		selector.Distinct()
	}
	for _, p := range thq.predicates {
		p(selector)
	}
	for _, p := range thq.order {
		p(selector)
	}
	if offset := thq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := thq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TaskHistoryGroupBy is the group-by builder for TaskHistory entities.
type TaskHistoryGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (thgb *TaskHistoryGroupBy) Aggregate(fns ...AggregateFunc) *TaskHistoryGroupBy {
	thgb.fns = append(thgb.fns, fns...)
	return thgb
}

// Scan applies the group-by query and scans the result into the given value.
func (thgb *TaskHistoryGroupBy) Scan(ctx context.Context, v any) error {
	query, err := thgb.path(ctx)
	if err != nil {
		return err
	}
	thgb.sql = query
	return thgb.sqlScan(ctx, v)
}

func (thgb *TaskHistoryGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range thgb.fields {
		if !taskhistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := thgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := thgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (thgb *TaskHistoryGroupBy) sqlQuery() *sql.Selector {
	selector := thgb.sql.Select()
	aggregation := make([]string, 0, len(thgb.fns))
	for _, fn := range thgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(thgb.fields)+len(thgb.fns))
		for _, f := range thgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(thgb.fields...)...)
}

// TaskHistorySelect is the builder for selecting fields of TaskHistory entities.
type TaskHistorySelect struct {
	*TaskHistoryQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ths *TaskHistorySelect) Aggregate(fns ...AggregateFunc) *TaskHistorySelect {
	ths.fns = append(ths.fns, fns...)
	return ths
}

// Scan applies the selector query and scans the result into the given value.
func (ths *TaskHistorySelect) Scan(ctx context.Context, v any) error {
	if err := ths.prepareQuery(ctx); err != nil {
		return err
	}
	ths.sql = ths.TaskHistoryQuery.sqlQuery(ctx)
	return ths.sqlScan(ctx, v)
}

func (ths *TaskHistorySelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(ths.fns))
	for _, fn := range ths.fns {
		aggregation = append(aggregation, fn(ths.sql))
	}
	switch n := len(*ths.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		ths.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		ths.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := ths.sql.Query()
	if err := ths.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
